### Arrays

In [ ]:
### contigous collection of data of same data type
# a contigous block of 1-D memory is allocated in memory for 1-D, 2-D, 3-D arrays

import array ## only arrays with same datatype can be made
import numpy as np
# arr = array.array('i')
# print(arr)
# arr = array.array('i', [1,2,3,4])
# print(arr)
# print(arr[0])

# import numpy as np
# arr = np.array([1,2,3,4], dtype=int)
# print(arr)
# print(arr[2])

# ### Inserting data
# arr = array.array('i',[1,2,3,4])
# arr2 = array.array('d', [1.2, 3.5, 6.33, 5.55])
# arr.insert(0, -1) # inserts -1 at 0th index
# arr.append(5)
# print(arr)

# ### traversal
# # for i in arr:
# #     print(i)

# ### searching 
# # if 5 in arr:
# #     print(True)

# ### delete an element
# # arr.remove(4)
# # print(arr)

# #   Created by Elshad Karimov on 04/04/2020.
# #   Copyright © 2020 AppMillers. All rights reserved.
# from array import *

# # 1. Create an array and traverse. 

# my_array = array('i',[1,2,3,4,5])

# for i in my_array:
#     print(i)


# # 2. Access individual elements through indexes
# print("Step 2")
# print(my_array[3])

# # 3. Append any value to the array using append() method

# print("Step 3")
# my_array.append(6)
# print(my_array)

# # 4. Insert value in an array using insert() method
# print("Step 4")
# my_array.insert(3, 11)
# print(my_array)


# # 5. Extend python array using extend() method
# print("Step 5")
# my_array1 = array('i', [10,11,12])
# my_array.extend(my_array1)
# print(my_array)

# # 6. Add items from list into array using fromlist() method
# print("Step 6")
# tempList = [20,21,22]
# my_array.fromlist(tempList)
# print(my_array)

# # 7. Remove any array element using remove() method
# print("Step 7")
# my_array.remove(11)
# print(my_array)

# # 8. Remove last array element using pop() method
# print("Step 8")
# my_array.pop()
# print(my_array)

# # 9. Fetch any element through its index using index() method
# print("Step 9")
# print(my_array.index(21))

# # 10. Reverse a python array using reverse() method
# print("Step 10")
# my_array.reverse()
# print(my_array)

# # 11. Get array buffer information through buffer_info() method
# print("Step 11")
# print(my_array.buffer_info())

# # 12. Check for number of occurrences of an element using count() method
# print("Step 12")
# my_array.append(11)
# print(my_array.count(11))
# print(my_array)
# # 13. Convert array to string using tostring() method
# print("Step 13")
# strTemp = my_array.tobytes()
# print(strTemp)
# ints = array('i')
# ints.frombytes(strTemp)
# print(ints)

# # 14. Convert array to a python list with same elements using tolist() method
# print("Step 14")
# # print(my_array.tolist())
# # 15. Append a string to char array using fromstring() method

# # 16. Slice Elements from an array
# print("Step 16")
# print(my_array[:])


### 2D Array
arr = np.array([[1, 2], [3, 4]])
# Insert a row at index 1
new_arr = np.insert(arr, 1, [9, 9], axis=0)
print(new_arr)

twoDArray = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(twoDArray)
twoDArray = np.insert(twoDArray, 0, [[-1,-1,-1,-1]], axis=0) ## 0 for rows and 1 for columns
print(twoDArray)
twoDArray = np.delete(twoDArray, 0, axis=1)
print(twoDArray)

## when to use/avoid array
# use: store multiple variables of same type and search takes O(1) time
# avoid: same data type and reserve memory -- when exeeds it allocates a larger array affecting performance

# | Goal                         | Use           |
# | ---------------------------- | ------------- |
# | Flexibility & mixed types    | `list`        |
# | Efficiency with uniform data | `array.array` |
# | Heavy math/data analysis     | `numpy.array` |



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[-1 -1 -1 -1]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[-1 -1 -1]
 [ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [ ]:
### Exercise
# avg temperatures
import numpy as np
temperatures = np.array([0,0,0], dtype=int)
for i in range(3):
    temp = input(f"What is temperature of {i+1} day? : ")
    temperatures[i] = temp
print(f"Avg Temperature of 3 days is {temperatures.mean()}")
days = len([x for x in temperatures if x > 15])
print(days)

Avg Temperature of 3 days is 15.0
1


### Dictionaries

In [ ]:
# Dictionaries

# Tuples

# linked lists

# stacks
#   Implementation using classes and objects

# queues
#   Implementation 
    # 1. using classes and objects

    # 2. from collections import deque
    # dq = deque(maxlen=4)
    # dq.append(1)
    # dq.append(2)
    # dq.append(3)
    # dq.append(4)
    # dq.append(5)
    # print(dq)
    # print(dq.popleft())
    # print(dq)
    # dq.clear()
    # print(dq)

    # 3. import queue as q
    # queue = q.Queue(maxsize=3)
    # print(queue.empty())
    # queue.put(1)
    # queue.put(2)
    # queue.put(3)
    # # queue.put(4)
    # print(queue.empty())
    # print(queue.qsize())
    # print(queue.full())
    # print(queue.get(1))
    # print(queue.qsize())




True
False
3
True
1
2


In [24]:
### Trees

# level order traversal

class Node:
    def __init__(self, value):
        self.value = value
        self.leftNode = None
        self.rightNode = None

class Tree:
    def __init__(self, rootNodeValue):
        self.rootNode = Node(rootNodeValue)

    def appendChild(self, childValue, root):
        
        childNode = Node(childValue)
        
        if root.leftNode is None:
            root.leftNode = childNode
        elif root.rightNode is None:
            root.rightNode = childNode
        else:
            pass
    
t1 = Tree(1)
print(t1.rootNode.value)
t1.appendChild(2, t1.rootNode)
t1.appendChild(3, t1.rootNode)


### level order traversal

from collections import deque

def levelOrderTraversal(root):
    if root is None:
        return
    
    q = deque()
    q.append(root)

    while len(q):

        sz = len(q)

        while sz:
            r = q.popleft()
            
            print(r.value, end=" ")
            
            if r.leftNode is not None:
                q.append(r.leftNode)
            
            if r.rightNode is not None:
                q.append(r.rightNode)
            
            sz -= 1
        
        print('\n')
        
levelOrderTraversal(t1.rootNode)


1
1 

2 3 



### Heaps

In [ ]:
# # heapq examples in Python

# import heapq

# # ✅ 1. Convert a list to a heap
# nums = [4, 1, 7, 3, 8, 5]
# heapq.heapify(nums)
# print("Heapified list:", nums)

# # ✅ 2. Push an element into the heap
# heapq.heappush(nums, 2)
# print("After pushing 2:", nums)

# # ✅ 3. Pop the smallest element
# smallest = heapq.heappop(nums)
# print("Popped smallest element:", smallest)
# print("Heap after popping:", nums)

# # ✅ 4. Peek at the smallest element (without popping)
# print("Peek at smallest element:", nums[0])

# # ✅ 5. Replace the smallest element and maintain heap
# heapq.heapreplace(nums, 6)
# print("After heapreplace with 6:", nums)

# # ✅ 6. Get n smallest and n largest elements
# lst = [5, 1, 3, 6, 2, 9]
# print("3 smallest elements:", heapq.nsmallest(3, lst))
# print("2 largest elements:", heapq.nlargest(2, lst))

# # ✅ 7. Priority Queue example (as min-heap using tuples)
# pq = []
# heapq.heappush(pq, (2, "Task 2"))
# heapq.heappush(pq, (1, "Task 1"))
# heapq.heappush(pq, (3, "Task 3"))

# print("\nPriority Queue:")
# while pq:
#     print(heapq.heappop(pq))  # Pops tasks in order of priority (lowest first)

# # ✅ Time Complexity Summary (for reference in comments)
# """
# Operation         Time Complexity
# ----------------  ----------------
# heapify           O(n)
# heappush          O(log n)
# heappop           O(log n)
# heapreplace       O(log n)
# nsmallest/nlargest O(n log k)
# """


### Sorting Algorithm

In [5]:
# Bubble Sort
# Best: O(n), Average: O(n^2), Worst: O(n^2)
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]

# Selection Sort
# Best: O(n^2), Average: O(n^2), Worst: O(n^2)
def selection_sort(arr):
    n = len(arr)
    for i in range(n):
        min_idx = i
        for j in range(i+1, n):
            if arr[j] < arr[min_idx]:
                min_idx = j
        arr[i], arr[min_idx] = arr[min_idx], arr[i]

# Insertion Sort
# Best: O(n), Average: O(n^2), Worst: O(n^2)
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i-1
        while j >= 0 and arr[j] > key:
            arr[j+1] = arr[j]
            j -= 1
        arr[j+1] = key

# Bucket Sort (for non-negative numbers)
# Best: O(n + k), Average: O(n + k), Worst: O(n^2) (if all in one bucket)
def bucket_sort(arr):
    if not arr:
        return
    max_val = max(arr)
    size = max_val / len(arr)
    buckets = [[] for _ in range(len(arr))]
    for i in range(len(arr)):
        idx = int(arr[i] / size)
        if idx != len(arr):
            buckets[idx].append(arr[i])
        else:
            buckets[len(arr) - 1].append(arr[i])
    for bucket in buckets:
        insertion_sort(bucket)
    k = 0
    for bucket in buckets:
        for val in bucket:
            arr[k] = val
            k += 1

# Bucket Sort with Negative Numbers
# Best: O(n + k), Average: O(n + k), Worst: O(n^2)
def bucket_sort_with_negatives(arr):
    if not arr:
        return
    min_val = min(arr)
    max_val = max(arr)
    range_val = max_val - min_val
    size = range_val / len(arr) + 1e-9
    buckets = [[] for _ in range(len(arr))]
    for i in range(len(arr)):
        idx = int((arr[i] - min_val) / size)
        buckets[idx].append(arr[i])
    for bucket in buckets:
        insertion_sort(bucket)
    k = 0
    for bucket in buckets:
        for val in bucket:
            arr[k] = val
            k += 1

# Merge Sort
# Best: O(n log n), Average: O(n log n), Worst: O(n log n)
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        L = arr[:mid]
        R = arr[mid:]
        merge_sort(L)
        merge_sort(R)
        i = j = k = 0
        while i < len(L) and j < len(R):
            if L[i] < R[j]:
                arr[k] = L[i]
                i += 1
            else:
                arr[k] = R[j]
                j += 1
            k += 1
        while i < len(L):
            arr[k] = L[i]
            i += 1
            k += 1
        while j < len(R):
            arr[k] = R[j]
            j += 1
            k += 1

# Quick Sort
# Best: O(n log n), Average: O(n log n), Worst: O(n^2)
def quick_sort(arr):
    def _quick_sort(arr, low, high):
        if low < high:
            pi = partition(arr, low, high)
            _quick_sort(arr, low, pi - 1)
            _quick_sort(arr, pi + 1, high)

    def partition(arr, low, high):
        pivot = arr[high]
        i = low - 1
        for j in range(low, high):
            if arr[j] <= pivot:
                i += 1
                arr[i], arr[j] = arr[j], arr[i]
        arr[i+1], arr[high] = arr[high], arr[i+1]
        return i + 1

    _quick_sort(arr, 0, len(arr) - 1)

# Heap Sort
# Best: O(n log n), Average: O(n log n), Worst: O(n log n)
def heap_sort(arr):
    def heapify(arr, n, i):
        largest = i
        l = 2*i + 1
        r = 2*i + 2
        if l < n and arr[l] > arr[largest]:
            largest = l
        if r < n and arr[r] > arr[largest]:
            largest = r
        if largest != i:
            arr[i], arr[largest] = arr[largest], arr[i]
            heapify(arr, n, largest)

    n = len(arr)
    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)
    for i in range(n - 1, 0, -1):
        arr[0], arr[i] = arr[i], arr[0]
        heapify(arr, i, 0)


### Graphs

In [ ]:
# DFS (Stack)
# BFS (Queue)
# topological sort using Stacks
# single source shortest path -- 3 ways to solve -- BFS, Djikstra and Bellman Ford ALgo
# For sssp BFS doesnt work for weighted graphs




In [8]:
s = "abc"
f = s
f = "dev"
print(s)

abc


In [ ]:
a = {1,2,3}
b = {3,4,5}
a.intersection(b)
a.difference(b)
a = "abc"

{1, 2}

In [23]:
chr(ord('A')+25)

'Z'

In [29]:
s = {'A':1}
s.setdefault('B', 2)
s

{'A': 1, 'B': 2}

In [30]:
s = "ABCD"
s[2:1]

''